//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaNegocio.ServiceReferenceWsfAlumnos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemTablaIsr", Namespace="http://schemas.datacontract.org/2004/07/WCFAlumnos")]
    [System.SerializableAttribute()]
    public partial class ItemTablaIsr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal cuotaFijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal excedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal isrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal limiteInferiorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal limiteSuperiorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal subsidioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal cuotaFija {
            get {
                return this.cuotaFijaField;
            }
            set {
                if ((this.cuotaFijaField.Equals(value) != true)) {
                    this.cuotaFijaField = value;
                    this.RaisePropertyChanged("cuotaFija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal excedente {
            get {
                return this.excedenteField;
            }
            set {
                if ((this.excedenteField.Equals(value) != true)) {
                    this.excedenteField = value;
                    this.RaisePropertyChanged("excedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal isr {
            get {
                return this.isrField;
            }
            set {
                if ((this.isrField.Equals(value) != true)) {
                    this.isrField = value;
                    this.RaisePropertyChanged("isr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal limiteInferior {
            get {
                return this.limiteInferiorField;
            }
            set {
                if ((this.limiteInferiorField.Equals(value) != true)) {
                    this.limiteInferiorField = value;
                    this.RaisePropertyChanged("limiteInferior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal limiteSuperior {
            get {
                return this.limiteSuperiorField;
            }
            set {
                if ((this.limiteSuperiorField.Equals(value) != true)) {
                    this.limiteSuperiorField = value;
                    this.RaisePropertyChanged("limiteSuperior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal subsidio {
            get {
                return this.subsidioField;
            }
            set {
                if ((this.subsidioField.Equals(value) != true)) {
                    this.subsidioField = value;
                    this.RaisePropertyChanged("subsidio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AportacionesImss", Namespace="http://schemas.datacontract.org/2004/07/WCFAlumnos")]
    [System.SerializableAttribute()]
    public partial class AportacionesImss : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal cesantíaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal enfermedadMaternidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal infonavitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal invalidezVidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal retiroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal cesantía {
            get {
                return this.cesantíaField;
            }
            set {
                if ((this.cesantíaField.Equals(value) != true)) {
                    this.cesantíaField = value;
                    this.RaisePropertyChanged("cesantía");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal enfermedadMaternidad {
            get {
                return this.enfermedadMaternidadField;
            }
            set {
                if ((this.enfermedadMaternidadField.Equals(value) != true)) {
                    this.enfermedadMaternidadField = value;
                    this.RaisePropertyChanged("enfermedadMaternidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal infonavit {
            get {
                return this.infonavitField;
            }
            set {
                if ((this.infonavitField.Equals(value) != true)) {
                    this.infonavitField = value;
                    this.RaisePropertyChanged("infonavit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal invalidezVida {
            get {
                return this.invalidezVidaField;
            }
            set {
                if ((this.invalidezVidaField.Equals(value) != true)) {
                    this.invalidezVidaField = value;
                    this.RaisePropertyChanged("invalidezVida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal retiro {
            get {
                return this.retiroField;
            }
            set {
                if ((this.retiroField.Equals(value) != true)) {
                    this.retiroField = value;
                    this.RaisePropertyChanged("retiro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWsfAlumnos.IWCFAlumnos")]
    public interface IWCFAlumnos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumnos/CalcularIsr", ReplyAction="http://tempuri.org/IWCFAlumnos/CalcularIsrResponse")]
        CapaNegocio.ServiceReferenceWsfAlumnos.ItemTablaIsr CalcularIsr(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumnos/CalcularIsr", ReplyAction="http://tempuri.org/IWCFAlumnos/CalcularIsrResponse")]
        System.Threading.Tasks.Task<CapaNegocio.ServiceReferenceWsfAlumnos.ItemTablaIsr> CalcularIsrAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumnos/CalcularImss", ReplyAction="http://tempuri.org/IWCFAlumnos/CalcularImssResponse")]
        CapaNegocio.ServiceReferenceWsfAlumnos.AportacionesImss CalcularImss(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumnos/CalcularImss", ReplyAction="http://tempuri.org/IWCFAlumnos/CalcularImssResponse")]
        System.Threading.Tasks.Task<CapaNegocio.ServiceReferenceWsfAlumnos.AportacionesImss> CalcularImssAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFAlumnosChannel : CapaNegocio.ServiceReferenceWsfAlumnos.IWCFAlumnos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFAlumnosClient : System.ServiceModel.ClientBase<CapaNegocio.ServiceReferenceWsfAlumnos.IWCFAlumnos>, CapaNegocio.ServiceReferenceWsfAlumnos.IWCFAlumnos {
        
        public WCFAlumnosClient() {
        }
        
        public WCFAlumnosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFAlumnosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAlumnosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAlumnosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaNegocio.ServiceReferenceWsfAlumnos.ItemTablaIsr CalcularIsr(int id) {
            return base.Channel.CalcularIsr(id);
        }
        
        public System.Threading.Tasks.Task<CapaNegocio.ServiceReferenceWsfAlumnos.ItemTablaIsr> CalcularIsrAsync(int id) {
            return base.Channel.CalcularIsrAsync(id);
        }
        
        public CapaNegocio.ServiceReferenceWsfAlumnos.AportacionesImss CalcularImss(int id) {
            return base.Channel.CalcularImss(id);
        }
        
        public System.Threading.Tasks.Task<CapaNegocio.ServiceReferenceWsfAlumnos.AportacionesImss> CalcularImssAsync(int id) {
            return base.Channel.CalcularImssAsync(id);
        }
    }
}
